
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class DataSupplier

    Public Property Kode_Supplier As String

    Public Property Nama_Supplier As String

    Public Property Alamat As String

    Public Property Kota As String

    Public Property Telepon As String

    Public Property Delete As String

    Public Property ID As Integer



    Public Overridable Property DataPembelian As ICollection(Of DataPembelian) = New HashSet(Of DataPembelian)


End Class
