
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class DataBarang

    Public Property Kode_Barang As String

    Public Property Nama_Barang As String

    Public Property Kode_Kelompok As String

    Public Property Stok As Integer

    Public Property Satuan As String

    Public Property Harga_beli As Long

    Public Property Harga_Jual As Long

    Public Property Delete As String

    Public Property ID As Integer



    Public Overridable Property DataKelompok As DataKelompok

    Public Overridable Property DetailPesanan As ICollection(Of DetailPesanan) = New HashSet(Of DetailPesanan)

    Public Overridable Property DetailPembelian As ICollection(Of DetailPembelian) = New HashSet(Of DetailPembelian)


End Class
