
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class DataPelunasan

    Public Property No_Pelunasan As String

    Public Property No_Piutang As String

    Public Property Tanggal As Nullable(Of Date)

    Public Property Bayar As Nullable(Of Long)

    Public Property Delete As String

    Public Property ID As Integer



    Public Overridable Property DataPiutang As DataPiutang


End Class
