
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class DataPelanggan

    Public Property Kode_Pelanggan As String

    Public Property Nama_Pelanggan As String

    Public Property Alamat As String

    Public Property Kota As String

    Public Property Telepon As String

    Public Property Delete As String

    Public Property ID As Integer



    Public Overridable Property DataPenjualan As ICollection(Of DataPenjualan) = New HashSet(Of DataPenjualan)

    Public Overridable Property DataPesanan As ICollection(Of DataPesanan) = New HashSet(Of DataPesanan)

    Public Overridable Property DataPiutang As ICollection(Of DataPiutang) = New HashSet(Of DataPiutang)


End Class
