'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DataPesanan
    Public Property No_Pesanan As String
    Public Property Kode_Pelanggan As String
    Public Property Tanggal As Date
    Public Property Sub_Total As Long
    Public Property Diskon1 As Decimal
    Public Property PPN1 As Decimal
    Public Property Diskon2 As Decimal
    Public Property PPN2 As Decimal
    Public Property Total As Decimal
    Public Property Digunakan As String
    Public Property Delete As String
    Public Property ID As Integer

    Public Overridable Property DataPelanggan As DataPelanggan
    Public Overridable Property DetailPesanan As ICollection(Of DetailPesanan) = New HashSet(Of DetailPesanan)
    Public Overridable Property DataPenjualan As ICollection(Of DataPenjualan) = New HashSet(Of DataPenjualan)

End Class
