
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class DataTerminPelunasan

    Public Property No_Termin As String

    Public Property No_Penjualan As String

    Public Property Jumlah_Termin As Integer



    Public Overridable Property DataPenjualan As DataPenjualan


End Class
