
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class DetailPembelian

    Public Property ID As Long

    Public Property No_Pembelian As String

    Public Property Kode_Barang As String

    Public Property Nama_Barang As String

    Public Property Qty As Integer

    Public Property Satuan As String

    Public Property Harga As Decimal

    Public Property Sub_Total As Decimal



    Public Overridable Property DataBarang As DataBarang

    Public Overridable Property DataPembelian As DataPembelian


End Class
