'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetailPenjualan
    Public Property ID As Integer
    Public Property No_Penjualan As String
    Public Property Kode_Barang As String
    Public Property Qty As Nullable(Of Integer)
    Public Property Harga As Nullable(Of Long)
    Public Property Sub_Total As Nullable(Of Long)

End Class
