'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property DataKelompok() As DbSet(Of DataKelompok)
    Public Property DataPelanggan() As DbSet(Of DataPelanggan)
    Public Property DataPelunasan() As DbSet(Of DataPelunasan)
    Public Property DataPesanan() As DbSet(Of DataPesanan)
    Public Property DataUser() As DbSet(Of DataUser)
    Public Property DetailPenjualan() As DbSet(Of DetailPenjualan)
    Public Property DetailPesanan() As DbSet(Of DetailPesanan)
    Public Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Property DataSupplier() As DbSet(Of DataSupplier)
    Public Property DataBarang() As DbSet(Of DataBarang)
    Public Property DataPenjualan() As DbSet(Of DataPenjualan)
    Public Property DataPiutang() As DbSet(Of DataPiutang)

End Class
